# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)
#
Location.create!([
  {name: 'Colorado State Capitol', address: '200 East Colfax Avenue, Denver, CO, 80203'},
  {name: 'Washington State Capitol', address: '416 Sid Snyder Avenue Southwest, Olympia, WA, 98504'},
  {name: 'New Jersey State House', address: '125 West State Street, Trenton, NJ, 8608'},
  {name: 'Kansas State Capitol', address: '300 Southwest 10th Avenue, Topeka, KS, 66612'},
  {name: 'Illinois State Capitol', address: '401 South 2nd Street, Springfield, IL, 62706'},
  {name: 'Georgia State Capitol', address: '206 Washington Street Southwest, Atlanta, GA, 30334'},
  {name: 'Ohio Statehouse', address: '1 Capitol Square, Columbus, OH, 43215'},
  {name: 'New Mexico State Capitol', address: '489 Old Santa Fe Trail, Santa Fe, NM, 87501'},
  {name: 'Oregon State Capitol', address: '900 Court Street Northeast, Salem, OR, 97301'},
  {name: 'California State Capitol', address: '1315 10th Street, Sacramento, CA, 95814'},
  {name: 'Virginia State Capitol', address: '1000 Bank Street, Richmond, VA, 23219'},
  {name: 'Rhode Island State House', address: '82 Smith Street, Providence, RI, 2903'},
  {name: 'South Dakota State Capitol', address: '500 East Capitol Avenue, Pierre, SD, 57501'},
  {name: 'Arizona State Capitol', address: '1700 West Washington Street, Phoenix, AZ, 85007'},
  {name: 'Oklahoma State Capitol', address: '2300 North Lincoln Boulevard, Oklahoma City, OK, 73105'},
  {name: 'Tennessee State Capitol', address: '600 Charlotte Avenue, Nashville, TN, 37219'},
  {name: 'Vermont State House', address: '115 State Street, Montpelier, VT, 5633'},
  {name: 'Alabama State Capitol', address: '600 Dexter Avenue, Montgomery, AL, 36130'},
  {name: 'Wisconsin State Capitol', address: '2 East Main Street, Madison, WI, 53703'},
  {name: 'Arkansas State Capitol', address: '500 Woodlane Street ,Little Rock, AR, 72201'},
  {name: 'Nebraska State Capitol', address: '1445 K Street, Lincoln, NE, 68508'},
  {name: 'Michigan State Capitol', address: 'Capitol Avenue and Michigan Avenue, Lansing, MI, 48909'},
  {name: 'Mississippi State Capitol', address: '400 High Street, Jackson, MS, 39201'},
  {name: 'Indiana State House', address: '200 West Washington Street, Indianapolis, IN, 46204'},
  {name: 'Montana State Capitol', address: '1301 East 6th Avenue, Helena, MT, 59601'},
  {name: 'Connecticut State Capitol', address: '210 Capitol Avenue, Hartford, CT, 6106'},
  {name: 'Pennsylvania Capitol', address: 'North 3rd Street and State Street, Harrisburg, PA, 17120'},
  {name: 'Iowa State Capitol', address: 'East 9th Street and Grand Avenue, Des Moines, IA, 50307'},
  {name: 'South Carolina State House', address: '11 Gervais Street, Columbia, SC, 29201'},
  {name: 'Wyoming State Capitol', address: '200 West 24th Street, Cheyenne, WY, 82002'},
  {name: 'West Virginia State Capitol', address: '1900 Kanawha Boulevard East, Charleston, WV, 25305'},
  {name: 'Nevada State Capitol', address: '101 North Carson Street, Carson City, NV, 89701'},
  {name: 'Louisiana State Capitol', address: 'North 3rd Street and State Capitol Drive, Baton Rouge, LA, 70802'},
  {name: 'Texas State Capitol', address: '1100 Congress Avenue, Austin, TX, 78701'},
  {name: 'Maryland State House', address: '100 State Circle, Annapolis, MD, 21401'},
  {name: 'New York State Capitol', address: 'State Street, Albany, NY, 12224'},
  {name: 'Missouri State Capitol', address: '201 West Capitol Avenue, Jefferson City, MO, 65101'},
  {name: 'Alaska State Capitol', address: '120 East 4th Avenue, Juneau, AK, 99801'},
  {name: 'Legislative Hall', address: '411 Legislative Avenue, Dover, DE, 19901'},
  {name: 'The Capitol', address: '400 South Monroe Street, Tallahassee, FL, 32399'},
  {name: 'Hawaii State Capitol', address: '415 South Beretania Street, Honolulu, HI, 96813'},
  {name: 'Idaho State Capitol', address: '700 West Jefferson Street, Boise, ID, 83702'},
  {name: 'Kentucky State Capitol', address: '700 Capitol Avenue Loop, Frankfort, KY, 40601'},
  {name: 'New Hampshire State House', address: '107 North Main Street, Concord, NH, 3301'},
  {name: 'Maine State House', address: '210 State Street, Augusta, ME, 4330'},
  {name: 'Massachusetts State House', address: 'Beacon Street and Park Street, Boston, MA, 2108'},
  {name: 'Minnesota State Capitol', address: '75 Reverend Doctor Martin Luther King Junior Boulevard, Saint Paul, MN, 55155'},
  {name: 'North Carolina State Capitol', address: '1 East Edenton Street, Raleigh, NC, 27601'},
  {name: 'North Dakota State Capitol', address: '600 East Boulevard Avenue, Bismarck, ND, 58505'},
  {name: 'Utah State Capitol', address: '350 North State Street, Salt Lake City, UT, 84103'},
  {name: 'United States Capitol', address: 'Independence Avenue and 1st Street, Washington, DC, 20016'},
  {name: 'A. P. Lutali Executive Office Building', address: '50001 EOB Loop, Pago Pago, AS, 96799'},
  {name: 'Capitol of Puerto Rico', address: '208 Calle O\'Donnell, San Juan, PR, 901'},
  {name: 'Capitol Building', address: 'Veterans Drive at Forte Strade, Charlotte Amalie Saint Thomas, VI, 804'},
  {name: 'Guam Legislature Building', address: '155 Hesler Place, Hagatna, GU, 96910'},
  {name: 'Juan A. Sablan Memorial Building', address: 'Isa Drive and Pagan Loop, Saipan, MP, 96950'}
])
